version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:7.11.2
    environment:
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9200
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  kibana:
    image: kibana:7.11.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - elk
    ports:
      - 5601:5601
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  worker:
    image: phasi/http_bomber
    command: ["-timeout", "2", "-duration", "15", "-export", "-el-url", "http://elasticsearch:9200/test/_doc", "-url", "http://example.org", "-n", "tcp4", "-headers", "Host:example.com"]
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

networks:
  elk: